import { relations } from 'drizzle-orm';
import {
	geometry,
	index,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	text,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';

/**
 * Referaly domain schema.
 *
 * Auth tables (user, session, account, verification) are generated by
 * Better Auth into `./auth-schema.ts` — run `npm run auth:generate`.
 */

/** Scan types offered by imaging clinics (matches the current Referaly filters). */
export const scanTypeEnum = pgEnum('scan_type', [
	'x_ray',
	'ultrasound',
	'ct',
	'mri',
	'mammography',
	'nuclear_medicine',
	'bone_density',
]);

export type ScanType = (typeof scanTypeEnum.enumValues)[number];

/** Who reported the current wait-time value for a clinic+scan type. */
export const reportedByEnum = pgEnum('reported_by', ['clinic', 'patient']);

/** Lifecycle of a clinic's request to claim/manage its listing. */
export const claimStatusEnum = pgEnum('claim_status', [
	'pending',
	'approved',
	'rejected',
]);

function idColumn() {
	return text('id')
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID());
}

function timestamps() {
	return {
		createdAt: timestamp('created_at', { withTimezone: true })
			.defaultNow()
			.notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true })
			.defaultNow()
			.notNull()
			.$onUpdate(() => new Date()),
	};
}

export const clinics = pgTable('clinics', {
	id: idColumn(),
	name: text('name').notNull(),
	about: text('about'),
	phone: text('phone'),
	email: text('email'),
	website: text('website'),
	languages: text('languages').array(),
	...timestamps(),
});

export const locations = pgTable(
	'locations',
	{
		id: idColumn(),
		clinicId: text('clinic_id')
			.notNull()
			.references(() => clinics.id, { onDelete: 'cascade' }),
		label: text('label'),
		address: text('address').notNull(),
		city: text('city'),
		province: text('province'),
		postalCode: text('postal_code'),
		/** WGS84 point, stored as (longitude, latitude). */
		geom: geometry('geom', { type: 'point', mode: 'xy', srid: 4326 }),
		/** Opening hours, e.g. { mon: ["09:00","17:00"], ... } — shape TBD in Phase 1. */
		hours: jsonb('hours'),
		...timestamps(),
	},
	(table) => [
		index('locations_clinic_id_idx').on(table.clinicId),
		// Spatial index powering viewport (bbox) map queries in Phase 2.
		index('locations_geom_gist_idx').using('gist', table.geom),
	],
);

export const services = pgTable(
	'services',
	{
		id: idColumn(),
		clinicId: text('clinic_id')
			.notNull()
			.references(() => clinics.id, { onDelete: 'cascade' }),
		scanType: scanTypeEnum('scan_type').notNull(),
		...timestamps(),
	},
	(table) => [
		index('services_clinic_id_idx').on(table.clinicId),
		uniqueIndex('services_clinic_scan_unique').on(
			table.clinicId,
			table.scanType,
		),
	],
);

export const waitTimes = pgTable(
	'wait_times',
	{
		id: idColumn(),
		clinicId: text('clinic_id')
			.notNull()
			.references(() => clinics.id, { onDelete: 'cascade' }),
		scanType: scanTypeEnum('scan_type').notNull(),
		/** Estimated wait in calendar days. */
		days: integer('days').notNull(),
		reportedBy: reportedByEnum('reported_by').notNull().default('clinic'),
		/** Patient "was this accurate?" confirmations. */
		confirmations: integer('confirmations').notNull().default(0),
		/** Patient "report actual wait" submissions against this value. */
		disputes: integer('disputes').notNull().default(0),
		reportedAt: timestamp('reported_at', { withTimezone: true })
			.defaultNow()
			.notNull(),
		...timestamps(),
	},
	(table) => [
		index('wait_times_clinic_id_idx').on(table.clinicId),
		uniqueIndex('wait_times_clinic_scan_unique').on(
			table.clinicId,
			table.scanType,
		),
	],
);

export const clinicClaims = pgTable(
	'clinic_claims',
	{
		id: idColumn(),
		clinicId: text('clinic_id')
			.notNull()
			.references(() => clinics.id, { onDelete: 'cascade' }),
		/** References Better Auth's `user.id` (auth-schema.ts). No FK: auth tables are managed by Better Auth. */
		userId: text('user_id').notNull(),
		status: claimStatusEnum('status').notNull().default('pending'),
		decidedAt: timestamp('decided_at', { withTimezone: true }),
		...timestamps(),
	},
	(table) => [
		index('clinic_claims_clinic_id_idx').on(table.clinicId),
		index('clinic_claims_user_id_idx').on(table.userId),
	],
);

export const clinicsRelations = relations(clinics, ({ many }) => ({
	locations: many(locations),
	services: many(services),
	waitTimes: many(waitTimes),
	claims: many(clinicClaims),
}));

export const locationsRelations = relations(locations, ({ one }) => ({
	clinic: one(clinics, {
		fields: [locations.clinicId],
		references: [clinics.id],
	}),
}));

export const servicesRelations = relations(services, ({ one }) => ({
	clinic: one(clinics, {
		fields: [services.clinicId],
		references: [clinics.id],
	}),
}));

export const waitTimesRelations = relations(waitTimes, ({ one }) => ({
	clinic: one(clinics, {
		fields: [waitTimes.clinicId],
		references: [clinics.id],
	}),
}));

export const clinicClaimsRelations = relations(clinicClaims, ({ one }) => ({
	clinic: one(clinics, {
		fields: [clinicClaims.clinicId],
		references: [clinics.id],
	}),
}));
